# Generated by Django 4.0.1 on 2022-11-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.CharField(default='Якийсь текст статті', max_length=255, verbose_name='Текст статті'),
            preserve_default=False,
        ),
    ]
